version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "hs-bg-sam-artifacts-us-east-1"
s3_prefix = "sam-app"
region = "us-east-1"
resolve_s3 = false
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []